### ISSUE TITLE
[Bug]: VOD movies return HTTP 500 on v0.22.0 — MultiWorkerVODConnectionManager missing `user` parameter

### ISSUE THREAD

**Issue by znake-oil** [Dispatcharr/Dispatcharr#1178]
### Describe the bug

A clear and concise description of what the bug is. What did you expect to happen?### Describe the bug

## Describe the bug

All VOD **movie** streams return HTTP 500 immediately after upgrading to v0.22.0. Series episodes are unaffected. Downgrading to v0.21.1 restores movie playback.

## How to reproduce

1. Run v0.22.0
2. Attempt to play any VOD movie via Emby, Jellyfin, Plex, or directly via the `/proxy/vod/movie/` endpoint
3. HTTP 500 is returned immediately — no stream starts

## Expected behavior

Movie streams play normally, as they did in v0.21.1.

## Logs
```
2026-04-04 07:05:11,301 INFO  apps.proxy.vod_proxy.views [VOD-STREAM] Calling connection manager to stream content
2026-04-04 07:05:11,301 ERROR apps.proxy.vod_proxy.views [VOD-EXCEPTION] Error streaming movie a0986f7f-...: MultiWorkerVODConnectionManager.stream_content_with_session() got an unexpected keyword argument 'user'
Traceback (most recent call last):
  File "/app/apps/proxy/vod_proxy/views.py", line 482, in stream_vod
    response = connection_manager.stream_content_with_session(
        session_id=session_id,
        ...
        user=user,
    )
TypeError: MultiWorkerVODConnectionManager.stream_content_with_session() got an unexpected keyword argument 'user'
```

## Root cause analysis

The new **User Stream Limits** feature (#544) updated `vod_proxy/views.py` to pass `user=user` into `stream_content_with_session()` — needed for per-user limit enforcement and username display on the Stats page (#766). However, `MultiWorkerVODConnectionManager.stream_content_with_session()` was never updated to accept this new parameter.

Series episodes are unaffected

## Version

- Dispatcharr: v0.22.0 (broken), v0.21.1 (working)
- Deployment: Docker AIO

## Additional context

Curl confirms the 500 is returned server-side immediately after the session redirect:
```
HTTP/1.1 301 → /proxy/vod/movie/{id}/vod_{session}
HTTP/1.1 500 Internal Server Error (Content-Length: 120)
```

### How can we recreate this bug?

1. Go to '...' 2. Click on '....' 3. Scroll down to '....' 4. See error

### Dispatcharr Version

0.22.2

### Docker Version

28.5.2+dfsg

### What's in your Docker Compose file?

If not using Docker Compose just put not using.

### Client Information

Device, App, Versions for both, etc...

### How can we recreate this bug?

1. Go to '...' 2. Click on '....' 3. Scroll down to '....' 4. See error

### Dispatcharr Version

0.22.2

### Docker Version

28.5.2+dfsg3

### What's in your Docker Compose file?

.

### Client Information

Device, App, Versions for both, etc...

**Comment by SergeantPanda** [comment]
I can not reproduce this bug. From what I can tell, that code was all changed at the same time so I do not know how you ran into it. Do you use any plugins or patches that are modifying the code?

**Comment by znake-oil** [comment]
I just got time to circle back to this, and I found it was only my own fault. I was mounting a patched version of multi_worker_connection_manager.py and it had the error. This can be closed as PEBKAC.
